#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.


set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind \
                          -plugin-tag package(js_of_ocaml.ocamlbuild)"}

action ()
{
    case $1 in
      default)      action backends ;;
      doc)          shift; pkg-doc $* doc/dev-api.docdir ;;
      api-doc)      shift; pkg-doc $* doc/api.docdir ;;
      backends)     $OCAMLBUILD useri_base.cma useri_base.cmxa \
                                useri.cma useri.cmxa \
                                useri_jsoo.cma useri_jsoo.cmxa \
                                useri_tsdl.cma useri_tsdl.cmxa
                    ;;
      tests)        $OCAMLBUILD tests.otarget ;;
      clean)        $OCAMLBUILD -clean ;;
      jsoo)         action backends
                    shift;
                    $OCAMLBUILD $1.cmo $1.html
                    # Work around ocamlbuild link order bug
                    cd _build
                    ocamlfind ocamlc -linkpkg -g \
                     -package js_of_ocaml -package js_of_ocaml.syntax \
                     -syntax camlp4o -package gg -package react \
                     src/useri_base.cma  src/jsoo/useri_jsoo.cma \
                     src/useri.cma test/test.cmo test/$1.cmo -o test/$1.byte
                    js_of_ocaml +weak.js test/test_jsoo.byte
                    reload-browser "http://`hostname`/useri/test/$1.html"
                    ;;
      *)            $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
